# render.yaml
services:
  - type: web
    name: scrapriq-api
    env: python
    pythonVersion: 3.12.6
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn scrapriq.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: SUPABASE_URL
        sync: false # Set this to false for sensitive data to prevent it from being synced to git
      - key: SUPABASE_KEY
        sync: false
      - key: SERP_API_KEY
        sync: false